CREATE TABLE IF NOT EXISTS employee
(
  employee_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  department_id INTEGER,
  job_title VARCHAR(64),
  gender INT,
  date_of_birth DATE
);